server:
  port: 8102
spring:
  application:
    name: auth-service


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xuanxuan8535
    url: jdbc:mysql://localhost:3306/travelplanner

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/

