server:
  port: 8801

spring:
  application:
    name: zuul-proxy

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/


zuul:
  routes:
    eureka-client:
      path: /test-service/**
    auth-service:
      path: /users/**

  add-host-header: true
  sensitive-headers: Cookie, Set-Cookie, Authorization

management:
  endpoints:
    web:
      exposure:
        include: '*'
