server:
  port: 8100

spring:
  application:
    name: elasticsearch

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
